ampta/config/routes.rb
Ampta::Application.routes.draw do
  get "users/index"

  get "home/index"
  get "home/login"
  get "home/logout"
  
  match "/home" => "home#index"

  match "/login" => "home#login"
  match "/logout" => "home#logout"

  match "/home/error" => "home#error"

  match "/do_login" => "home#do_login"

  resources :users
  
  resources :projects do
    resources :tickets
  end

  resources :tickets

  match "/register" => "users#new"
  

  root :to => 'home#login'

end

ampta/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :sidenav
  
  def index
   # ...
  end

  def error
    # ...
  end

end

ampta/app/helpers/home_helper.rb
module HomeHelper
end

ampta/app/views/home/error.html.erb
<% content_for :title, "Home" %>

<h3>Error</h3>
<p id="notice"><%= notice %></p>

ampta/app/views/home/index.html.erb
<% content_for :title, "Home" %>

<h3>Welcome to AMPTA project management system.</h3>
<p id="notice"><%= notice %></p>

ampta/app/views/home/login.html.erb
<div class="container">
	<div id="notice"><%= notice %></div>
	<div class="container">
		<div class="content">
			<div class="row">
				<div class="login-form">
					<h2>Login</h2>
					<%= form_for @user, :url => { :action => "do_login" } do |f| %>
						<fieldset>
							<div class="clearfix">
								<%= f.text_field :email, :placeholder => "E-mail" %>
							</div>
							<div class="clearfix">
								<%= f.password_field :password, :placeholder => "Password" %>
							</div>
							<%= f.submit "Login" %>
						</fieldset>
					<% end %>
				</div>
				<p class="pull-right"><%= link_to "Register", register_path %></p>
			</div>
		</div>
	</div>
</div>