ampta/config/routes.rb
Ampta::Application.routes.draw do
  get "users/index"

  get "home/index"
  get "home/login"
  get "home/logout"
  
  match "/home" => "home#index"

  match "/login" => "home#login"
  match "/logout" => "home#logout"

  match "/home/error" => "home#error"

  match "/do_login" => "home#do_login"

  resources :users
  
  resources :projects do
    resources :tickets
  end

  resources :tickets

  match "/register" => "users#new"
  

  root :to => 'home#login'

end

ampta/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :name, :description, :start_date, :end_date, :status_id, :project_id
  belongs_to :user
  belongs_to :project
  belongs_to :status

  validates :name,
            :presence => true,
            :uniqueness => { :scope => :project_id, :case_sensitive => false, :message => "already exists in this project" },
            :length => { :in => 3..30, :allow_blank => true }

  validates_presence_of :description, :start_date, :end_date

  validate :validate_end_date_before_start_date,
           :validate_start_date_in_project_scope,
           :validate_end_date_in_project_scope


  def validate_end_date_before_start_date
    if end_date && start_date
      errors.add(:end_date, "must be greater than start date") if end_date <= start_date
    end
  end

  def validate_end_date_in_project_scope
    if end_date && start_date
      p = Project.find(project_id)
      errors.add(:end_date, "cannot be later than project end date - #{p.end_date.to_date.to_formatted_s(:long_ordinal)}") if end_date > p.end_date
    end
  end

  def validate_start_date_in_project_scope
    if end_date && start_date
      p = Project.find(project_id)
      errors.add(:start_date, "cannot be earlier than project start date - #{p.start_date.to_date.to_formatted_s(:long_ordinal)}") if start_date < p.start_date
    end
  end

end

ampta/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :confirm_user_new, :only => [:new, :create, :show]
  before_filter :confirm_user_edit, :only => [:edit, :update, :destroy]
  before_filter :confirm_user_index, :only => [:index]
  before_filter :sidenav

  def index
    # if url: /tickets/ -show all tickets for user. if url: /project/id/tickets/ -show all tickets for project
    if params[:project_id]
      @project_name = Project.find(params[:project_id]).name
      @tickets = Ticket.where("project_id = ?", params[:project_id])
    else
      @tickets = Ticket.where("user_id = ?", user_logged_in)
    end
  end

  def show
    @ticket = Ticket.find(params[:id])

    # is ticket or project owner
    if @ticket.user_id == user_logged_in || @ticket.project.owner_id == user_logged_in
      @owner_menu = true
    end
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(params[:ticket])
    @ticket.user_id = user_logged_in

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to project_path(@ticket.project), :notice => "Ticket \"#{@ticket.name}\" was created." }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def update
    @ticket = Ticket.find(params[:id])
    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to project_ticket_path(@ticket.project, @ticket), :notice => "Ticket \"#{@ticket.name}\" was updated." }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to project_path(@ticket.project), :notice => 'Ticket was deleted.' }
    end
  end

  ##
  # check to see if user is ticket owner or project owner
  #
  def confirm_user_edit
    ticket =  Ticket.find(params[:id])
    unless ticket.user_id == user_logged_in || ticket.project.owner_id == user_logged_in
      flash[:notice] = "You don't have the permission to do that."
      redirect_to home_error_path
      return false
    else
      return true
    end
  end

  def confirm_user_new
    project = Project.find(params[:project_id]) 
    unless project.owner_id == user_logged_in || project.users.exists?(user_logged_in)
      flash[:notice] = "You don't have the permission to do that."
      redirect_to home_error_path
      return false
    else
      return true
    end
  end

  def confirm_user_index
    if params[:project_id] && !Project.find(params[:project_id]).users.exists?(user_logged_in)
      flash[:notice] = "You don't have the permission to do that."
      redirect_to home_error_path
      return false
    else
      return true
    end
  end

end

ampta/app/helpers/tickets_helper.rb
module TicketsHelper
end

ampta/app/views/tickets/_new_edit_form.html.erb
<% @ticket.errors.full_messages.each do |msg| %>
<p class="validationMsg alert alert-error"><%= msg %></p>
<% end %>

<%= form_for @ticket, :url => { :action => @the_action }, :html => { :class => "project_form" } do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, :length => { :minimum => 3, :maximum => 30} %><br />
	<%= f.label :description %>
	<%= f.text_area :description, :cols => 30, :rows => 20 %><br />
	<div class="form_date_option">
		<%= f.label :start_date, :cols => 22 %>
		<%= f.date_select :start_date %><br />
		<%= f.label :end_date %>
		<%= f.date_select :end_date %><br /><br />
	</div>

	<%= f.label :status %>
	<% if @ticket.id %>
		<%= f.select :status_id, options_from_collection_for_select(Status.all, :id, :status_name, :selected => @ticket.status.id) %>
	<% else %>
		<%= f.select :status_id, options_from_collection_for_select(Status.all, :id, :status_name) %>
	<% end %>
	<br /><br />

	<%= f.hidden_field :project_id, :value => params[:project_id] %>
	<%= f.submit %>
<% end %>

ampta/app/views/tickets/edit.html.erb
<% content_for :title, "Edit Ticket" %>
<% @the_action = "update" %>

<ul class="breadcrumb">
  <li><%= link_to "Home", home_path %> <span class="divider">/</span></li>
  <li><%= link_to "Projects", projects_path %> <span class="divider">/</span></li>
  <li><%= link_to @ticket.project.name, project_path(@ticket.project) %> <span class="divider">/</span></li>
  <li><%= link_to "Tickets", project_tickets_path(@ticket.project) %> <span class="divider">/</span></li>
  <li class="active"><%= @ticket.name %></li>
</ul>

<h3>Edit ticket</h3>
<%= render :partial => "new_edit_form"  %>

ampta/app/views/tickets/index.html.erb
<% content_for :title, "Tickets" %>

<% if @project_name  %>
<h3>Tickets for project <%= @project_name %></h3>
<% else  %>
<h3>Your tickets</h3>
<% end %>

<% if @tickets.size > 0 %>
	<ul>
	<% @tickets.each do |t| %>
		<li><%= link_to t.name, project_ticket_path(t.project, t) %></li>
	<% end %>
	</ul>
<% else %>
	<p>No tickets.</p>
<% end %>

ampta/app/views/tickets/new.html.erb
<% content_for :title, "New Ticket" %>
<% @the_action = "create" %>

<h3>New ticket</h3>
<%= render :partial => "new_edit_form"  %>

ampta/app/views/tickets/show.html.erb
<% content_for :title, "Ticket" %>

<ul class="breadcrumb">
  <li><%= link_to "Home", home_path %> <span class="divider">/</span></li>
  <li><%= link_to "Projects", projects_path %> <span class="divider">/</span></li>
  <li><%= link_to @ticket.project.name, project_path(@ticket.project) %> <span class="divider">/</span></li>
  <li><%= link_to "Tickets", project_tickets_path(@ticket.project) %> <span class="divider">/</span></li>
  <li class="active"><%= @ticket.name %></li>
</ul>

<h3><%= @ticket.name %></h3>
<p id="notice"><%= notice %></p>

<h4>Description</h4>
<p><%= @ticket.description %></p>

<h4>Time period</h4>
<p><strong>Start:</strong> <%= @ticket.start_date.to_date.to_formatted_s(:long_ordinal) %></p>
<p><strong>End:</strong> <%= @ticket.end_date.to_date.to_formatted_s(:long_ordinal) %></p>

<h4>Status</h4>
<p><%= @ticket.status.status_name %></p>

<h4>Owner</h4>
<p><%= link_to "#{@ticket.user.first_name} #{@ticket.user.last_name}", user_path(@ticket.user) %></p>

<% if @owner_menu %>
	<p class="btn btn-small">
		<%= link_to 'Edit ticket', edit_project_ticket_path(@ticket.project, @ticket) %>
	</p>
	<p class="btn btn-small">
		<%= link_to 'Delete ticket', @ticket, :confirm => 'Are you sure you want to delete this ticket?', :method => :delete %>
	</p>
<% end %>