ampta/config/routes.rb
Ampta::Application.routes.draw do
  get "users/index"

  get "home/index"
  get "home/login"
  get "home/logout"
  
  match "/home" => "home#index"

  match "/login" => "home#login"
  match "/logout" => "home#logout"

  match "/home/error" => "home#error"

  match "/do_login" => "home#do_login"

  resources :users
  
  resources :projects do
    resources :tickets
  end

  resources :tickets

  match "/register" => "users#new"
  

  root :to => 'home#login'

end

ampta/app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a id="logo" class="brand">Ampta</a>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="<%= 'active' if current_page?(root_path) || current_page?(home_index_path) || current_page?(home_path) %>">
            <%= link_to 'Home', home_path %>
          </li>
          <li class="<%= 'active' if current_page?(users_path) %>">
            <%= link_to 'All users', users_path %>
          </li>
          <li class="<%= 'active' if current_page?(projects_path) %>">
            <%= link_to 'All projects', projects_path %>
          </li>
          <li class="<%= 'active' if current_page?(new_project_path) %>">
            <%= link_to 'New project', new_project_path %>
          </li>
        </ul>
      </div>
      <span class="sign_out pull-right"><%= link_to 'Sign out', logout_path %></span>
      <span class="active_user pull-right"><%= @user_name %></span>

    </div>
  </div>
</nav>

ampta/app/views/layouts/_sidenav.html.erb
<div class="sidenav pull-left">
	<h5>Your projects</h5>
	<ul>
	<% @projects_nav.each do |p| %>
		<% if p.owner_id == session[:user_id] %>
			<% admin = '(admin)' %>
		<% else  %>
			<% admin = nil %>
		<% end %>
		<li><%= link_to p.name, project_path(p) %> <%= admin %></li>
	<% end %>
	</ul>

	<h5>Your latest <%= @tickets_nav.size %> tickets</h5>
	<ul>
	<% @tickets_nav.each do |t|  %>
		<li><%= link_to t.name, project_ticket_path(t.project, t) %></li>
	<% end %>
	</ul>
</div>

ampta/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AMPTA | <%= yield :title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<%= render :partial => "layouts/header" %>
		<%= render :partial => "layouts/sidenav" %>
		
		<div class="main pull-left">
			<%= yield %>
		</div>
	</div>
</body>
</html>

ampta/app/views/layouts/login_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AMPTA</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="../bootstrap.css" rel="stylesheet">
    <style type="text/css">
      /* Override some defaults */
      html, body {
        background-color: #eee;
      }
      body {
        padding-top: 40px; 
      }
      .container {
        width: 300px;
      }

      /* The white background content wrapper */
      .container > .content {
        background-color: #fff;
        padding: 20px;
        margin: 0 -20px; 
        -webkit-border-radius: 10px 10px 10px 10px;
           -moz-border-radius: 10px 10px 10px 10px;
                border-radius: 10px 10px 10px 10px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
                box-shadow: 0 1px 2px rgba(0,0,0,.15);
      }

	  .login-form {
		margin-left: 65px;
	  }
	
	  legend {
		margin-right: -50px;
		font-weight: bold;
	  	color: #404040;
	  }

    </style>
</head>
<body>
	<%= yield %>
</body>
</html>