ampta/config/routes.rb
Ampta::Application.routes.draw do
  get "users/index"

  get "home/index"
  get "home/login"
  get "home/logout"
  
  match "/home" => "home#index"

  match "/login" => "home#login"
  match "/logout" => "home#logout"

  match "/home/error" => "home#error"

  match "/do_login" => "home#do_login"

  resources :users
  
  resources :projects do
    resources :tickets
  end

  resources :tickets

  match "/register" => "users#new"
  

  root :to => 'home#login'

end

ampta/app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :description, :start_date, :end_date, :project_users
  has_and_belongs_to_many :users
  has_many :tickets, :dependent => :destroy

  validates :name,
            :presence => true,
            :uniqueness => { :scope => :owner_id, :case_sensitive => false, :message => "already exists in your other projects" },
            :length => { :in => 3..20, :allow_blank => true }
         
  validates_presence_of :description, :start_date, :end_date

  validate :validate_end_date_before_start_date

  
  def project_users=(project_users)
    # empty. defines attribute :project_users for join table
  end

  def validate_end_date_before_start_date
    if end_date && start_date
      errors.add(:end_date, "must be greater than start date") if end_date <= start_date
    end
  end

end

ampta/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :confirm_user, :only => [:edit, :update, :destroy]
  before_filter :confirm_user_show, :only => :show
  before_filter :sidenav

  def index
    @projects = Project.all # order...: Project.order("id DESC").all
  end

  def show
    @project = Project.find(params[:id])
    @project_owner = User.find(@project.owner_id)

    # is owner?
    if @project.owner_id == user_logged_in
      @owner_menu = true
    end

    # belongs to project?
    if @project.users.exists?(user_logged_in)
      @belongs_menu = true
    end
  end

  def new
    @project = Project.new
    @users = get_users_except_current
  end

  def create
    @users = get_users_except_current
    @project = Project.new(params[:project])
    @project.owner_id = user_logged_in

    respond_to do |format|
      if @project.save
        u = User.find(user_logged_in)
        u.projects << @project

        if params[:project][:project_users]
          params[:project][:project_users].each do |id| 
            @project.users << User.find(id)
          end
        end
        format.html { redirect_to project_path(@project), :notice => "Project was created." }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def edit
    @project = Project.find(params[:id])
    @users = get_users_except_current
  end

  def update
    @users = get_users_except_current
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        # clear join table
        @project.users.clear
        # current user
        u = User.find(user_logged_in)
        u.projects << @project
        if params[:project][:project_users]
          # add users to join table
          params[:project][:project_users].each do |id| 
            @project.users << User.find(id)
          end
        end
        format.html { redirect_to project_path(@project), :notice => "Project was updated." }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to home_index_path, :notice => 'Project was deleted.' }
    end
  end

  def get_users_except_current
    current_user = User.find(user_logged_in)
    @users = (current_user.blank? ? User.all : User.find(:all, :conditions => ["id != ?", current_user.id]))
  end

  ##
  # check to see if user is project owner
  #
  def confirm_user
    unless Project.find(params[:id]).owner_id == user_logged_in
      flash[:notice] = "You don't have the permission to do that."
      redirect_to home_error_path
      return false
    else
      return true
    end
  end

  def confirm_user_show
    project = Project.find(params[:id]) 
    unless project.owner_id == user_logged_in || project.users.exists?(user_logged_in)
      flash[:notice] = "You don't have the permission watch this project."
      redirect_to home_error_path
      return false
    else
      return true
    end
  end

end

ampta/app/helpers/projects_helper.rb
module ProjectsHelper
end

ampta/app/views/projects/_new_edit_form.html.erb
<% @project.errors.full_messages.each do |msg| %>
<p class="validationMsg alert alert-error"><%= msg %></p>
<% end %>

<%= form_for @project, :html => { :class => "project_form" } do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name, :length => { :minimum => 3, :maximum => 20} %><br />
	<%= f.label :description %>
	<%= f.text_area :description, :cols => 30, :rows => 20 %><br />
	<div class="form_date_option">
		<%= f.label :start_date, :cols => 22 %>
		<%= f.date_select :start_date %><br />
		<%= f.label :end_date %>
		<%= f.date_select :end_date %><br /><br />
	</div>

	<label>Users in project</label>
	<% @users.each do |u| %>
		<p>
			<%= "#{u.first_name} #{u.last_name}" %>
			<% if u.projects.exists?(@project.id) %>
				<% @checked = true %>
			<% else %>
				<% @checked = false %>
			<% end %>
			<%= check_box_tag "project[project_users][]", u.id, @checked %>
		</p>
	<% end %>
	<br /><br />

	<%= f.submit %>
<% end %>

ampta/app/views/projects/edit.html.erb
<% content_for :title, "Edit Project" %>

<ul class="breadcrumb">
  <li><%= link_to "Home", home_path %> <span class="divider">/</span></li>
  <li><%= link_to "Projects", projects_path %> <span class="divider">/</span></li>
  <li class="active"><%= @project.name %> <span class="divider">/</span></li>
  <li><%= link_to "Tickets", project_tickets_path(@project) %> </span></li>
</ul>

<h3>Edit project</h3>
<%= render :partial => "new_edit_form" %>

ampta/app/views/projects/index.html.erb
<% content_for :title, "Projects" %>

<h3>Projects involving you</h3>
<ul>
<% @projects.each do |p| %>
	<% if p.users.exists?(session[:user_id])  %>
		<li><%= link_to p.name, project_path(p) %></li>
	<% end %>
<% end %>
</ul>

<h3>Other projects</h3>
<ul>
<% @projects.each do |p| %>
	<% if !p.users.exists?(session[:user_id]) %>
		<li><%= p.name %></li>
	<% end %>
<% end %>
</ul>

ampta/app/views/projects/new.html.erb
<% content_for :title, "New Project" %>

<h3>New project</h3>
<%= render :partial => "new_edit_form" %>

ampta/app/views/projects/show.html.erb
<% content_for :title, "Project" %>

<ul class="breadcrumb">
  <li><%= link_to "Home", home_path %> <span class="divider">/</span></li>
  <li><%= link_to "Projects", projects_path %> <span class="divider">/</span></li>
  <li class="active"><%= @project.name %> <span class="divider">/</span></li>
  <li><%= link_to "Tickets", project_tickets_path(@project) %> </span></li>
</ul>

<h3><%= @project.name %></h3>
<p id="notice"><%= notice %></p>

<% if @belongs_menu  %>
	<p class="btn"><%= link_to "New ticket", new_project_ticket_path(@project)  %></p>
<% end %>

<h4>Description</h4>
<p><%= @project.description %></p>

<h4>Time period</h4>
<p><strong>Start:</strong> <%= @project.start_date.to_date.to_formatted_s(:long_ordinal) %></p>
<p><strong>End:</strong> <%= @project.end_date.to_date.to_formatted_s(:long_ordinal) %></p>

<h4>Project owner</h4>
<%= link_to "#{@project_owner.first_name} #{@project_owner.last_name}", user_path(@project_owner) %>

<h4>Users in this project:</h4>
<ul>
<% @project.users.each do |u| %>
	<li><%= link_to "#{u.first_name} #{u.last_name}", user_path(u) %></li>
<% end %>
</ul>

<h4>Tickets</h4>
<% if @project.tickets.size > 0 %>
	<ul>
	<% @project.tickets.each do |t| %>
		<li><%= link_to t.name, project_ticket_path(@project, t) %></li>
	<% end %>
	</ul>
<% else %>
	<p>No tickets.</p>
<% end %>


<% if @owner_menu %> 
	<p class="btn btn-small">
		<%= link_to 'Edit project', edit_project_path %>
	</p>
	<p class="btn btn-small">
		<%= link_to 'Delete project', @project, :confirm => 'Are you sure you want to delete this project?', :method => :delete  %>
	</p>
<% end %>